'use client';
import {useEffect,useState} from 'react';
import {Link2,Radio,Shield,ArrowDownToLine,Copy,Heart,Unplug,Plus,Check,Settings2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {SoulOnline,useSavedAccess} from '@/components/soul-online';
import {EncounterMap} from '@/components/encounter-map';
import type {CatchMon,CatchMember} from '@/lib/encounters.mjs';
type Mon=CatchMon&{level:number|null,hp:number|null,maxHp:number|null};
type Member={party:Mon[],seen:Mon[],dead:string[],lastSeen:number,teamSource?:string,teamCapturedAt?:number,encounters?:CatchMember['encounters']};
type State={John:Member,Eddie:Member,names:Record<string,string>};
type Access={id:string,readToken:string,John?:string,Eddie?:string};
const empty=():Member=>({party:[],seen:[],dead:[],lastSeen:0});
function teamStatus(member:Member,now:number){return member.teamSource==='live'&&member.teamCapturedAt&&now-member.teamCapturedAt<60000?`Live-Team · vor ${Math.max(0,Math.round((now-member.teamCapturedAt)/1000))} s`:'Team vom letzten Speichern';}
export default function Home(){const [access,setAccess]=useState<Access|null>(null),[state,setState]=useState<State>({John:empty(),Eddie:empty(),names:{}}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now()),[tab,setTab]=useState<'team'|'all'>('team'),[copied,setCopied]=useState(false),[edit,setEdit]=useState<number|null>(null),[draft,setDraft]=useState('');
useSavedAccess(access,setAccess);
useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
useEffect(()=>{if(!access)return;let active=true;const read=async()=>{try{const r=await fetch('/api/room?id='+access.id,{headers:{Authorization:'Bearer '+access.readToken}});const d:any=await r.json();if(!r.ok)throw Error(d.error);if(active){setState(d.state);setError('');setNow(Date.now());}}catch(e){if(active)setError((e as Error).message);}};read();const timer=setInterval(read,2000);return()=>{active=false;clearInterval(timer)}},[access]);
useEffect(()=>{const c=(document as any).modelContext;if(!c?.registerTool)return;const controller=new AbortController();Promise.resolve(c.registerTool({name:'read_soul_link_teams',description:'Liest die sichtbaren Teams und Paare dieser Spielrunde, ohne unbekannte Pokémon zu enthüllen.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:any)=>{if(input&&Object.keys(input).length)throw Error('Keine Parameter erwartet');return {connected:!!access,...state};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[state,access]);
async function create(){setBusy(true);try{const r=await fetch('/api/room',{method:'POST'}),d:any=await r.json();if(!r.ok)throw Error(d.error);setAccess(d);location.hash=new URLSearchParams({room:d.id,key:d.readToken}).toString();setError('');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
function download(player:'John'|'Eddie'){if(!access?.[player])return;const data={baseUrl:location.origin,roomId:access.id,player,token:access[player]};const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=`SoulLink_${player==='John'?'Anakin':'Obi-Wan'}.json`;a.click();URL.revokeObjectURL(u);}
async function rename(i:number){try{const r=await fetch('/api/room',{method:'PATCH',headers:{Authorization:'Bearer '+access!.readToken,'Content-Type':'application/json'},body:JSON.stringify({id:access!.id,pair:i,name:draft})});if(!r.ok)throw Error('Name konnte nicht gespeichert werden.');setState(s=>({...s,names:{...s.names,[i]:draft}}));setEdit(null);}catch(e){setError((e as Error).message)}}
const count=Math.max(state.John.seen.length,state.Eddie.seen.length);const dead=(i:number)=>(['John','Eddie'] as const).some(p=>state[p].seen[i]&&state[p].dead.includes(state[p].seen[i].uid));const deadCount=Array.from({length:count},(_,i)=>i).filter(dead).length;const indices=Array.from({length:count},(_,i)=>i).filter(i=>tab==='all'||(['John','Eddie'] as const).some(p=>state[p].seen[i]&&state[p].party.some(m=>m.uid===state[p].seen[i].uid)));
function card(p:'John'|'Eddie',i:number){const m=state[p].seen[i],locked=dead(i),team=m&&state[p].party.some(x=>x.uid===m.uid);return <div className={'mon '+(locked?'locked':'')}><div className="sprite">{m?<img src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${m.species}.png`} alt="" width="80" height="80" referrerPolicy="no-referrer"/>:<span>?</span>}</div><div className="mon-main"><div className="mon-name">{m?(m.nickname||`Pokémon #${m.species}`):'Noch kein Partner'}</div><div className="mon-meta">{m?<>{m.level?`Lv. ${m.level}`:'Box'} <span>·</span> {locked?'Gesperrt':team?'Im Team':'In der Box'}</>:'Wartet auf den nächsten Fang'}</div>{m&&m.maxHp!==null&&<div className="hp"><div style={{width:`${(m.hp||0)/m.maxHp*100}%`}}/></div>}</div><div className="hp-number">{m&&m.maxHp!==null?`${m.hp}/${m.maxHp}`:'—'}</div></div>}
return <main><header><div className="brand"><div className="brand-symbol"><Link2 size={25}/></div><div>SOUL<span>LINK</span><small>ANAKIN × OBI-WAN</small></div></div><div className="header-right"><span className="game">SOULSILVER · DE</span><span className="secure"><Shield size={15}/> Private Spielrunde</span></div></header>
<section className="title-row"><div><p className="eyebrow">EURE GEMEINSAME RUNDE</p><h1>Team. Fänge. Fortschritt<span>.</span></h1><p className="subtitle">Teams etwa alle 25 Sekunden. Bild und Ton bleiben in Discord.</p></div><div className="counter"><strong>{String(count).padStart(2,'0')}</strong><span>VERBINDUNGEN</span><b>{deadCount} verloren</b></div></section>
{error&&<div className="error" role="alert">{error} Eure gespeicherten Verbindungen bleiben erhalten.</div>}
{!access?<section className="connect"><div className="connect-icon"><Radio size={35}/></div><div><h2>Eure Spielrunde beginnt hier.</h2><p>Nach dem Speichern im Spiel sendet eure App den Teamstand. K. o. wird nur erkannt, wenn mit 0 KP gespeichert wurde.</p></div><Button onClick={create} disabled={busy} className="create">{busy?'Wird erstellt…':<><Plus size={18}/> Spielrunde erstellen</>}</Button></section>:<section className="access"><div><Shield size={18}/><span>Geheimer Runden-Link</span></div><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setError('Link bitte aus der Adresszeile kopieren.')}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Kopiert':'Runden-Link kopieren'}</Button></section>}
<SoulOnline access={access} onNew={create} members={state} now={now} blocked={{John:state.John.seen.filter((_,i)=>dead(i)).map(m=>m.uid),Eddie:state.Eddie.seen.filter((_,i)=>dead(i)).map(m=>m.uid)}}>
<EncounterMap access={access} members={state} onChange={(player,encounters)=>setState(s=>({...s,[player]:{...s[player],encounters}}))}/>
<h2 className="pair-heading">Eure Soul-Link-Paare</h2><section className="teams"><div className="player john"><div className="avatar">A</div><div><h2>Anakin</h2><span>{teamStatus(state.John,now)}</span></div><div className={'live '+(now-state.John.lastSeen<10000?'online':'')}><Radio size={14}/>{now-state.John.lastSeen<10000?'App verbunden':'Nicht verbunden'}</div></div><div className="middle-link"><Link2/></div><div className="player eddie"><div className="avatar">O</div><div><h2>Obi-Wan</h2><span>{teamStatus(state.Eddie,now)}</span></div><div className={'live '+(now-state.Eddie.lastSeen<10000?'online':'')}><Radio size={14}/>{now-state.Eddie.lastSeen<10000?'App verbunden':'Nicht verbunden'}</div></div></section>
<div className="list-header"><div className="view-buttons"><button aria-pressed={tab==='team'} onClick={()=>setTab('team')}>Paare im Team</button><button aria-pressed={tab==='all'} onClick={()=>setTab('all')}>Alle Verbindungen <span>{count}</span></button></div><span className="sync-note"><Radio size={14}/> Automatische Aktualisierung</span></div>
<section className="pair-list">{indices.length?indices.map(i=><article key={i} className={'pair '+(dead(i)?'dead':'')}><div className="pair-label"><span>LINK {String(i+1).padStart(3,'0')}</span>{edit===i?<form onSubmit={e=>{e.preventDefault();rename(i)}}><Input value={draft} onChange={e=>setDraft(e.target.value)} maxLength={32} autoFocus aria-label="Gemeinsamer Paarname"/><Button type="submit" size="sm">Speichern</Button><Button type="button" variant="ghost" size="sm" onClick={()=>setEdit(null)}>Abbrechen</Button></form>:<button onClick={()=>{setEdit(i);setDraft(state.names[i]||'')}}>{state.names[i]||`Verbindung ${i+1}`} <Settings2 size={13}/></button>}{dead(i)&&<b>Beide gesperrt</b>}</div><div className="pair-body">{card('John',i)}<div className="pair-chain">{dead(i)?<Unplug size={20}/>:<Link2 size={20}/>}</div>{card('Eddie',i)}</div></article>):<div className="empty"><div className="empty-link"><Link2 size={33}/></div><h2>{access?'Bereit für euren ersten Link.':'Eure Pokémon warten auf euch.'}</h2><p>{access?'Startet beide Emulator-Apps und wählt eure Starter selbst. Nach dem Speichern im Spiel erscheinen eure Teams hier.':'Erstellt eine Spielrunde, verbindet eure Apps und wählt eure Starter. Bis dahin bleibt alles eine Überraschung.'}</p><div className="empty-slots">{[0,1,2,3,4,5].map(i=><div key={i}><span>?</span></div>)}</div></div>}</section>
</SoulOnline><footer><span><Heart size={16}/> Ein Paar, ein Schicksal.</span><p>Paare entstehen in der Reihenfolge der erkannten Fänge. Der gemeinsame Name gilt hier im Tracker. Gesperrte Partner dürft ihr nach eurer Regel nicht einsetzen; die ROM wird dadurch nicht verändert.</p><a className="footer-tag" href="https://github.com/JohnLegendstyle/SoulLink/releases/latest" target="_blank" rel="noreferrer">APP & UPDATES ↗</a></footer></main>}


