import {typeInfo,typeNames} from '@/lib/pokemon-types.mjs';
export type LiveMon={uid:string,species:number,nickname:string,level:number|null,hp:number|null,maxHp:number|null};
export type LiveMember={party:LiveMon[],teamSource?:string,teamCapturedAt?:number};
export function LiveParty({member,player,now,blocked}:{member:LiveMember,player:string,now:number,blocked:string[]}){
  const live=member.teamSource==='live'&&!!member.teamCapturedAt&&now-member.teamCapturedAt<60000;
  return <aside className="live-party" aria-label={`Aktuelles Team von ${player}`}><div className="live-party-heading"><strong>Aktuelles Team</strong><span>{live?`Live · vor ${Math.max(0,Math.round((now-member.teamCapturedAt!)/1000))} s`:member.teamSource==='live'?'Letzter Live-Stand · veraltet':'Letzter Speicherstand'}</span></div>
    <ol>{Array.from({length:6},(_,i)=>{const mon=member.party[i];const locked=!!mon&&blocked.includes(mon.uid);const info=mon?typeInfo(mon.species):null;return <li key={mon?.uid||`empty-${i}`} className={locked?'party-locked':''}>{mon?<><img src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${mon.species}.png`} width="64" height="64" alt={`Pokémon #${mon.species}`} referrerPolicy="no-referrer"/><div><div className="party-name"><strong>{mon.nickname||`Pokémon #${mon.species}`}</strong><span>Lv. {mon.level??'?'}</span>{locked&&<i>Gesperrt</i>}</div><div className="type-badges" aria-label={`Typ ${info!.types.map(type=>typeNames[type]).join(' und ')}`}><small>Typ</small>{info!.types.map(type=><b key={type} data-type={type}>{typeNames[type]}</b>)}</div><small className="matchup"><em>Schwach</em> {info!.weak.length?info!.weak.map(item=>`${typeNames[item.type]}${item.multiplier===4?' ×4':''}`).join(' · '):'—'}</small>{mon.maxHp!=null&&<div className="party-hp"><div><span>KP</span><strong>{mon.hp??0} / {mon.maxHp}</strong></div><meter min={0} max={mon.maxHp} value={mon.hp??0} aria-label={`${mon.hp??0} von ${mon.maxHp} KP`}/></div>}</div></>:<><b className="party-slot">{i+1}</b><span>Freier Teamplatz</span></>}</li>;})}</ol>
    {!member.party.length&&<p>Noch kein Team übertragen.</p>}
  </aside>;
}
