import {env} from 'cloudflare:workers';
import {encounterFields,type CatchMon,type CatchMember} from './encounters.mjs';
export const db=()=> (env as unknown as {DB:D1Database}).DB;
export const hash=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,'0')).join('');
export const key=()=>crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');
export const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','Referrer-Policy':'no-referrer'}});
export type Mon=CatchMon&{level:number|null,hp:number|null,maxHp:number|null};
export type Position={mapId:number,x:number,y:number,direction:number,capturedAt:number,receivedAt:number};
export type Member={party:Mon[],seen:Mon[],dead:string[],lastSeen:number,sessionId:string,sequence:number,teamSource?:'live'|'save',teamCapturedAt?:number,position?:Position|null,encounters?:CatchMember['encounters']};
export type State={John:Member,Eddie:Member,names:Record<string,string>};
export function initial():State {const p=():Member=>({party:[],seen:[],dead:[],lastSeen:0,sessionId:'',sequence:-1,position:null});return {John:p(),Eddie:p(),names:{}};}
export async function authorize(req:Request,id:string){if(!/^[a-f0-9-]{36}$/.test(id))return null;const token=req.headers.get('authorization')?.replace(/^Bearer /,'');if(!token||token.length!==64)return null;const row=await db().prepare('SELECT * FROM rooms WHERE id = ?').bind(id).first<{id:string,read_hash:string,john_hash:string,eddie_hash:string,state:string,revision:number}>();if(!row)return null;const h=await hash(token);const role=h===row.john_hash?'John':h===row.eddie_hash?'Eddie':h===row.read_hash?'read':null;return role?{row,role,state:JSON.parse(row.state) as State}:null;}
export function blocked(state:State,player:'John'|'Eddie'){const partner=player==='John'?'Eddie':'John';return state[player].seen.filter((m,i)=>state[player].dead.includes(m.uid)||(state[partner].seen[i]&&state[partner].dead.includes(state[partner].seen[i].uid))).map(m=>m.uid);}
export function cleanMon(v:any):Mon {if(!v||typeof v.uid!=='string'||!v.uid.length||v.uid.length>100||!Number.isInteger(v.species)||v.species<1||v.species>493||!Number.isInteger(v.level)||v.level<1||v.level>100||!Number.isInteger(v.maxHp)||v.maxHp<1||v.maxHp>999||!Number.isInteger(v.hp)||v.hp<0||v.hp>v.maxHp)throw Error('Ungültiger Pokémon-Datensatz');return{uid:v.uid,species:v.species,nickname:String(v.nickname||'').slice(0,30),level:v.level,hp:v.hp,maxHp:v.maxHp,...encounterFields(v)};}
export function cleanOwned(v:any):Mon{if(v?.level!=null)return cleanMon(v);if(!v||typeof v.uid!=='string'||!v.uid.length||v.uid.length>100||!Number.isInteger(v.species)||v.species<1||v.species>493)throw Error('Ungültige Boxdaten');return {uid:v.uid,species:v.species,nickname:String(v.nickname||'').slice(0,30),level:null,hp:null,maxHp:null,...encounterFields(v)};}
export function cleanPosition(v:any):Position{if(!v||!Number.isInteger(v.mapId)||v.mapId<0||v.mapId>1000||!Number.isInteger(v.x)||v.x<0||v.x>100000||!Number.isInteger(v.y)||v.y<0||v.y>100000||!Number.isInteger(v.direction)||v.direction<0||v.direction>3||!Number.isSafeInteger(v.capturedAt)||v.capturedAt<1)throw Error('Ungültige Position');return{mapId:v.mapId,x:v.x,y:v.y,direction:v.direction,capturedAt:Math.min(v.capturedAt,Date.now()),receivedAt:Date.now()};}
